In [141]:
import pandas as pd
import numpy as np
import math

import MDAnalysis 

import bokeh_catplot

import bokeh.io
import bokeh.plotting

bokeh.io.output_notebook()

global dipole_vectors
global OW_array
global HW1_array
global HW2_array

Loading BokehJS ...

In [152]:
def read_OW_coordinates(position_file, trajectory_file):
    
    '''This function reads the coordinates of oxygen atoms in water molecules and returns an array of all coordinates.'''
    
    u = MDAnalysis.Universe(position_file, trajectory_file)
    OW_select = u.select_atoms('name OW')
    with MDAnalysis.Writer('Documents/prd1_OW.trr', OW_select.n_atoms) as W:
        for ts in u.trajectory:
            W.write(OW_select)
            OW_array = OW_select.positions
    return OW_array

In [132]:
def read_HW1_coordinates(position_file, trajectory_file):
    
    '''This function reads the coordinates of one set of hydrogren atoms in water molecules and returns an array of all coordinates.'''
    
    u1 = MDAnalysis.Universe(position_file, trajectory_file)
    HW1_select = u1.select_atoms('name HW1')
    with MDAnalysis.Writer('Documents/prd1_HW1.trr', HW1_select.n_atoms) as W:
        for ts1 in u1.trajectory:
            W.write(HW1_select)
            HW1_array = HW1_select.positions
    return HW1_array

In [134]:
def read_HW2_coordinates(position_file, trajectory_file):
    
    '''This function reads the coordinates of one set of hydrogren atoms in water molecules and returns an array of all coordinates.'''
    
    u2 = MDAnalysis.Universe(position_file, trajectory_file)
    HW2_select = u2.select_atoms('name HW2')
    with MDAnalysis.Writer('Documents/prd1_HW2.trr', HW2_select.n_atoms) as W:
        for ts2 in u2.trajectory:
            W.write(HW2_select)
            HW2_array = HW2_select.positions
    return HW2_array

In [155]:
def find_dipole_vector(position_file, trajectory_file):
    
    '''This function finds the dipole vector of each water molecule.'''
    
    vector_1_array = read_OW_coordinates(position_file, trajectory_file) - read_HW1_coordinates(position_file, trajectory_file)
    vector_2_array = read_OW_coordinates(position_file, trajectory_file) - read_HW2_coordinates(position_file, trajectory_file)
    dipole_vectors = vector_1_array + vector_2_array
    return dipole_vectors
find_dipole_vector('Documents/conf1.gro', 'Documents/prd2_full.trr')

[[-0.5300007  -0.16999626  1.0300007 ]
 [-0.06999969  0.6800003  -0.94000053]
 [-0.00999975  0.19999987  1.1500034 ]
 ...
 [-0.5400009   0.6800003   0.78999996]
 [ 0.8300009   0.22999954 -0.8100033 ]
 [-0.06000137 -0.8299999   0.829998  ]]


array([[-0.5300007 , -0.16999626,  1.0300007 ],
       [-0.06999969,  0.6800003 , -0.94000053],
       [-0.00999975,  0.19999987,  1.1500034 ],
       ...,
       [-0.5400009 ,  0.6800003 ,  0.78999996],
       [ 0.8300009 ,  0.22999954, -0.8100033 ],
       [-0.06000137, -0.8299999 ,  0.829998  ]], dtype=float32)

In [187]:
def angle_calc(vector_array):
    
    ''' This is a function to calculate the cosine of the angle formed by the y axis and dipole vector of each water molecule.'''
    
    # intialize variables
    ref_vector = np.array([0.000, 1.000, 0.000])
    unit_vector_2 = ref_vector / np.linalg.norm(ref_vector)
    
    vector_list = vector_array.tolist()
    
    cos_theta_list = []
    for i in range(0, len(vector_list)):
            unit_vector_1 = vector_list[i] / np.linalg.norm(vector_list[i])
            dot_product = np.dot(unit_vector_1, unit_vector_2)
            cos_theta_list.append(dot_product)
    return cos_theta_list
    

In [188]:
angle_calc(find_dipole_vector('Documents/conf1.gro', 'Documents/prd2_full.trr'))

[[-0.5300007  -0.16999626  1.0300007 ]
 [-0.06999969  0.6800003  -0.94000053]
 [-0.00999975  0.19999987  1.1500034 ]
 ...
 [-0.5400009   0.6800003   0.78999996]
 [ 0.8300009   0.22999954 -0.8100033 ]
 [-0.06000137 -0.8299999   0.829998  ]]


[-0.1452004714441403,
 0.5850557951708977,
 0.17133428217041602,
 0.3017821765877662,
 -0.6888696051032859,
 -0.38321847434990175,
 -0.9994375427570548,
 -0.7460301168220513,
 0.6676422230932735,
 0.2618204423308204,
 0.5608933395993072,
 -0.007293981541521336,
 0.5377938481958686,
 -0.051899887105637796,
 0.4000611550702893,
 -0.7414874542249129,
 -0.7060809683476615,
 -0.22954784918823726,
 -0.11192281121951503,
 0.09329742092025074,
 -0.23136023700013245,
 0.644298718130302,
 -0.7982293599246376,
 -0.7557416046253128,
 0.2712829977444322,
 -0.26584197613869015,
 -0.4784217126326439,
 -0.9996714159185222,
 0.4529580811527579,
 0.6827887485593277,
 0.960815676845858,
 0.23737331005969275,
 0.8131252515150448,
 0.034214719975376194,
 0.2733949688351906,
 -0.38460191516218717,
 -0.01385704903955459,
 -0.6936705879001579,
 -0.21308651844482002,
 -0.33985105841476004,
 -0.3940867208744161,
 -0.5553934036029828,
 -0.5734666809860492,
 -0.33434903987373565,
 0.661389498263376,
 -0.346438182